import { AppStore } from "./stores/app.store";

export interface ActivityData {
  id: number;
  title: string;
  description?: string;
  latitude: number;
  longitude: number;
  durationHours: number;
  interests: AppStore["filter"]["interests"][];
  ages: {
    from: number;
    to: number;
  };
}

export const activitiesMockData: ActivityData[] = [
  {
    id: 1,
    title: "Mirabell Palace and Gardens",
    description: "A beautiful palace with stunning gardens, famous for 'Sound of Music'.",
    latitude: 47.8095,
    longitude: 13.055,
    durationHours: 2,
    interests: ["Art & Culture", "History & Architecture", "Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 2,
    title: "Hohensalzburg Fortress",
    description: "Majestic fortress above the city with panoramic views.",
    latitude: 47.7946,
    longitude: 13.0468,
    durationHours: 3,
    interests: ["History & Architecture", "Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 3,
    title: "Mozart's Birthplace",
    description: "The birthplace of W.A. Mozart on Getreidegasse.",
    latitude: 47.8005,
    longitude: 13.0435,
    durationHours: 1.5,
    interests: ["History & Architecture", "Music & Festivals", "Art & Culture"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 4,
    title: "Salzburg Cathedral (Dom)",
    description: "Impressive baroque cathedral in the heart of the old town.",
    latitude: 47.7979,
    longitude: 13.0468,
    durationHours: 1,
    interests: ["History & Architecture", "Art & Culture"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 5,
    title: "Hellbrunn Palace & Trick Fountains",
    description: "Pleasure palace with world-famous, surprising trick fountains.",
    latitude: 47.761,
    longitude: 13.061,
    durationHours: 3,
    interests: ["Family & Kids", "History & Architecture", "Art & Culture"],
    ages: { from: 4, to: 99 },
  },
  {
    id: 6,
    title: "Haus der Natur (House of Nature)",
    description: "Natural history and technology museum with aquarium and science center.",
    latitude: 47.8009,
    longitude: 13.0401,
    durationHours: 4,
    interests: ["Family & Kids", "Art & Culture"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 7,
    title: "Augustiner Bräu - Mülln Monastery",
    description: "Traditional brewery with a large beer garden and self-service.",
    latitude: 47.8082,
    longitude: 13.0375,
    durationHours: 2.5,
    interests: ["Food & Drink"],
    ages: { from: 16, to: 99 },
  },
  {
    id: 8,
    title: "Stroll along Getreidegasse",
    description: "Famous shopping street with historic guild signs.",
    latitude: 47.8,
    longitude: 13.043,
    durationHours: 1.5,
    interests: ["History & Architecture", "Food & Drink"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 9,
    title: "Hangar-7",
    description: "Museum for airplanes, Formula 1 cars, and art, with a gourmet restaurant.",
    latitude: 47.7945,
    longitude: 13.0076,
    durationHours: 2,
    interests: ["Art & Culture", "Food & Drink"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 10,
    title: "Stiegl-Brauwelt (Stiegl World of Brewing)",
    description: "Brewery experience with museum, guided tour, and tasting.",
    latitude: 47.7925,
    longitude: 13.021,
    durationHours: 2.5,
    interests: ["Food & Drink", "History & Architecture"],
    ages: { from: 16, to: 99 },
  },
  {
    id: 11,
    title: "The Original Sound of Music Tour",
    description: "Bus tour to the famous filming locations in and around Salzburg.",
    latitude: 47.8095,
    longitude: 13.055,
    durationHours: 4,
    interests: ["Music & Festivals", "Art & Culture"],
    ages: { from: 5, to: 99 },
  },
  {
    id: 12,
    title: "Museum der Moderne Mönchsberg",
    description: "Modern art museum with spectacular views over the city.",
    latitude: 47.8011,
    longitude: 13.041,
    durationHours: 2,
    interests: ["Art & Culture"],
    ages: { from: 10, to: 99 },
  },
  {
    id: 13,
    title: "Untersberg Cable Car",
    description: "Cable car up Salzburg's local mountain for hiking and views.",
    latitude: 47.717,
    longitude: 13.045,
    durationHours: 3,
    interests: ["Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 14,
    title: "Zoo Salzburg Hellbrunn",
    description: "Zoo at the foot of Hellbrunn Mountain, near the palace.",
    latitude: 47.755,
    longitude: 13.0615,
    durationHours: 3,
    interests: ["Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 15,
    title: "DomQuartier Salzburg",
    description: "Tour through the Residence, Cathedral, and St. Peter's Abbey.",
    latitude: 47.798,
    longitude: 13.046,
    durationHours: 2.5,
    interests: ["History & Architecture", "Art & Culture"],
    ages: { from: 10, to: 99 },
  },
  {
    id: 16,
    title: "Salzburg Marionette Theater",
    description: "World-famous puppet theater, often performing Mozart operas.",
    latitude: 47.8035,
    longitude: 13.045,
    durationHours: 2,
    interests: ["Music & Festivals", "Art & Culture", "Family & Kids"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 17,
    title: "Coffee Break at Café Tomaselli",
    description: "Austria's oldest coffee house on the Old Market Square (Alter Markt).",
    latitude: 47.799,
    longitude: 13.0465,
    durationHours: 1,
    interests: ["Food & Drink", "History & Architecture"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 18,
    title: "Original Salzburg Mozartkugel at Fürst",
    description: "Try the original Mozartkugel (chocolate confection).",
    latitude: 47.7988,
    longitude: 13.046,
    durationHours: 0.5,
    interests: ["Food & Drink", "History & Architecture"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 19,
    title: "Dinner at St. Peter Stiftskulinarium",
    description: "One of Europe's oldest restaurants, located in St. Peter's Abbey.",
    latitude: 47.797,
    longitude: 13.045,
    durationHours: 2.5,
    interests: ["Food & Drink", "History & Architecture"],
    ages: { from: 12, to: 99 },
  },
  {
    id: 20,
    title: "Mozart Dinner Concert",
    description: "Classical concert in historical costumes accompanied by dinner.",
    latitude: 47.797,
    longitude: 13.045,
    durationHours: 3,
    interests: ["Music & Festivals", "Food & Drink", "Art & Culture"],
    ages: { from: 10, to: 99 },
  },
  {
    id: 21,
    title: "Guided Tour of the Festival Halls",
    description: "A look behind the scenes of the Salzburg Festival.",
    latitude: 47.799,
    longitude: 13.04,
    durationHours: 1.5,
    interests: ["Music & Festivals", "History & Architecture", "Art & Culture"],
    ages: { from: 10, to: 99 },
  },
  {
    id: 22,
    title: "Salzach River Cruise",
    description: "Boat tour on the Salzach river to Hellbrunn with the 'Amadeus'.",
    latitude: 47.802,
    longitude: 13.044,
    durationHours: 1.5,
    interests: ["Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 23,
    title: "Toy Museum (Spielzeug Museum)",
    description: "Historical toys to look at and try out.",
    latitude: 47.8,
    longitude: 13.0395,
    durationHours: 2,
    interests: ["Family & Kids", "History & Architecture"],
    ages: { from: 0, to: 14 },
  },
  {
    id: 24,
    title: "Mozart's Residence",
    description: "The Mozart family's later residence on Makartplatz.",
    latitude: 47.803,
    longitude: 13.047,
    durationHours: 1.5,
    interests: ["History & Architecture", "Music & Festivals", "Art & Culture"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 25,
    title: "St. Peter's Cemetery & Catacombs",
    description: "Salzburg's oldest cemetery with catacombs carved into the rock.",
    latitude: 47.7968,
    longitude: 13.0455,
    durationHours: 1,
    interests: ["History & Architecture"],
    ages: { from: 8, to: 99 },
  },
  {
    id: 26,
    title: "Walk on the Mönchsberg",
    description: "Hiking trail above the left bank of the old town with great views.",
    latitude: 47.799,
    longitude: 13.038,
    durationHours: 2,
    interests: ["Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 27,
    title: "Walk on the Kapuzinerberg",
    description: "Path to the Capuchin monastery, overlooking the old town.",
    latitude: 47.803,
    longitude: 13.049,
    durationHours: 1.5,
    interests: ["Family & Kids", "History & Architecture"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 28,
    title: "Salzburg Museum - New Residence",
    description: "The museum about the city's history, located in the New Residence.",
    latitude: 47.7985,
    longitude: 13.0475,
    durationHours: 2,
    interests: ["History & Architecture", "Art & Culture"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 29,
    title: "Visit the Schrannenmarkt",
    description: "Traditional weekly market (Thursdays) near the Andräkirche.",
    latitude: 47.806,
    longitude: 13.047,
    durationHours: 1.5,
    interests: ["Food & Drink", "Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 30,
    title: "Trip up the Gaisberg",
    description: "Viewpoint accessible by car or bus (Line 151).",
    latitude: 47.805,
    longitude: 13.111,
    durationHours: 2.5,
    interests: ["Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 31,
    title: "Old Town Tour: Hidden Alleys",
    description: "Guided walk through the lesser-known passageways.",
    latitude: 47.7995,
    longitude: 13.0445,
    durationHours: 2,
    interests: ["History & Architecture"],
    ages: { from: 12, to: 99 },
  },
  {
    id: 32,
    title: "Modern Gallery 'ArtSpace'",
    description: "Local artists exhibit in the ArtSpace near Mirabell Gardens.",
    latitude: 47.807,
    longitude: 13.048,
    durationHours: 1,
    interests: ["Art & Culture"],
    ages: { from: 10, to: 99 },
  },
  {
    id: 33,
    title: "Cooking Class: Salzburger Nockerl",
    description: "Learn to make the famous sweet soufflé yourself.",
    latitude: 47.804,
    longitude: 13.051,
    durationHours: 3,
    interests: ["Food & Drink", "Family & Kids"],
    ages: { from: 10, to: 99 },
  },
  {
    id: 34,
    title: "Horse-Drawn Carriage Ride (Fiaker)",
    description: "Fiaker ride through the old town, starting from Residenzplatz.",
    latitude: 47.7985,
    longitude: 13.047,
    durationHours: 0.75,
    interests: ["History & Architecture", "Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 35,
    title: "Visit the Holy Trinity Church",
    description: "Significant church building by Fischer von Erlach.",
    latitude: 47.8035,
    longitude: 13.0465,
    durationHours: 0.5,
    interests: ["History & Architecture", "Art & Culture"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 36,
    title: "Craft Beer Tasting 'Die Hopfenkultur'",
    description: "Tasting of local and international craft beers.",
    latitude: 47.808,
    longitude: 13.041,
    durationHours: 2,
    interests: ["Food & Drink"],
    ages: { from: 18, to: 99 },
  },
  {
    id: 37,
    title: "Medieval Museum (Fictional)",
    description: "A (fictional) museum about medieval Salzburg.",
    latitude: 47.795,
    longitude: 13.046,
    durationHours: 1.5,
    interests: ["History & Architecture", "Family & Kids"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 38,
    title: "Open-Air Cinema (Summer)",
    description: "Film screenings on Kapitelplatz during the summer.",
    latitude: 47.797,
    longitude: 13.0475,
    durationHours: 2.5,
    interests: ["Music & Festivals", "Art & Culture"],
    ages: { from: 12, to: 99 },
  },
  {
    id: 39,
    title: "Jazz Club 'Blue Note Hall'",
    description: "Live jazz music in a cellar vault.",
    latitude: 47.8005,
    longitude: 13.0415,
    durationHours: 3,
    interests: ["Music & Festivals", "Food & Drink"],
    ages: { from: 18, to: 99 },
  },
  {
    id: 40,
    title: "Mirabell Playground (Magic Flute)",
    description: "Large themed playground in the shadow of the Mirabell Gardens.",
    latitude: 47.809,
    longitude: 13.048,
    durationHours: 1.5,
    interests: ["Family & Kids"],
    ages: { from: 0, to: 12 },
  },
  {
    id: 41,
    title: "City Riddle Tour (Self-Guided)",
    description: "A scavenger hunt through the old town via an app.",
    latitude: 47.8,
    longitude: 13.045,
    durationHours: 2.5,
    interests: ["Family & Kids", "History & Architecture"],
    ages: { from: 8, to: 99 },
  },
  {
    id: 42,
    title: "Ice Cream at Eis-Greissler",
    description: "Popular ice cream parlor in the old town.",
    latitude: 47.7998,
    longitude: 13.0455,
    durationHours: 0.5,
    interests: ["Food & Drink", "Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 43,
    title: "Photo Tour: Best Viewpoints",
    description: "Guided tour to the best photo spots on the city mountains.",
    latitude: 47.8015,
    longitude: 13.0405,
    durationHours: 3,
    interests: ["Art & Culture"],
    ages: { from: 14, to: 99 },
  },
  {
    id: 44,
    title: "Nonnberg Abbey",
    description: "Oldest nunnery, known from 'Sound of Music'.",
    latitude: 47.794,
    longitude: 13.051,
    durationHours: 1,
    interests: ["History & Architecture", "Music & Festivals"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 45,
    title: "Traditional Bosna Stand (Balkan Grill)",
    description: "The local sausage specialty in one of the famous passages.",
    latitude: 47.8001,
    longitude: 13.0439,
    durationHours: 0.25,
    interests: ["Food & Drink"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 46,
    title: "Christmas Market at Domplatz (Winter)",
    description: "One of the most famous Christmas markets in the world.",
    latitude: 47.7979,
    longitude: 13.0468,
    durationHours: 2,
    interests: ["Music & Festivals", "Food & Drink", "Family & Kids"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 47,
    title: "Sternbräu Beer Garden",
    description: "Large, traditional beer garden complex in the old town.",
    latitude: 47.7995,
    longitude: 13.042,
    durationHours: 2,
    interests: ["Food & Drink"],
    ages: { from: 0, to: 99 },
  },
  {
    id: 48,
    title: "Georg Trakl Memorial Site",
    description: "Museum and memorial for the poet Georg Trakl.",
    latitude: 47.801,
    longitude: 13.047,
    durationHours: 1,
    interests: ["Art & Culture", "History & Architecture"],
    ages: { from: 16, to: 99 },
  },
  {
    id: 49,
    title: "Salzburg State Theatre (Landestheater)",
    description: "Performances of opera, drama, and ballet.",
    latitude: 47.804,
    longitude: 13.044,
    durationHours: 3,
    interests: ["Music & Festivals", "Art & Culture"],
    ages: { from: 12, to: 99 },
  },
  {
    id: 50,
    title: "Salzburg Climbing Hall (Fictional)",
    description: "Modern climbing and bouldering hall in the Lehen district.",
    latitude: 47.815,
    longitude: 13.03,
    durationHours: 2.5,
    interests: ["Family & Kids"],
    ages: { from: 6, to: 99 },
  },
  {
    id: 51,
    title: "Residenzgalerie",
    description: "European painting from the 16th to the 19th century.",
    latitude: 47.7986,
    longitude: 13.047,
    durationHours: 1.5,
    interests: ["Art & Culture", "History & Architecture"],
    ages: { from: 10, to: 99 },
  },
  {
    id: 52,
    title: "Tour 'Jewish Salzburg'",
    description: "Guided walking tour on the history of the Jewish community.",
    latitude: 47.805,
    longitude: 13.0445,
    durationHours: 2,
    interests: ["History & Architecture"],
    ages: { from: 14, to: 99 },
  },
];
