import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InterestsFilter from "@/components/filter/InterestsFilter";
import PersonsFilter from "@/components/filter/PersonsFilter";
import DurationFilter from "@/components/filter/DurationFilter";
import PlannedActivitiesFilter from "@/components/filter/PlannedActivitiesFilter";
import ChatBot from "@/components/ChatBot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex items-stretch h-screen">
          <div className="shrink-0 w-[350px] border-r p-5 flex flex-col gap-10 pt-10 overflow-y-auto">
            <InterestsFilter />
            <PersonsFilter />
            <DurationFilter />
            <PlannedActivitiesFilter />
          </div>

          <main className="flex-1 p-10 overflow-y-auto">{children}</main>
        </div>
        <ChatBot />
      </body>
    </html>
  );
}
